server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/prabodhadarshani/microservice-course-on-youtube-config-store
          search-paths:
            - 'service-config/*service'

          #username: root
          #passphrase: 123